name: 安全检查
on:
  pull_request:
    branches:    
      - master

jobs:
  secret-check:
    name: 安全密钥检查
    runs-on: ubuntu-latest
    steps:
      - run: curl https://raw.githubusercontent.com/stormeyes/maifangke-web/master/check.sh | bash -s ${GITHUB_HEAD_REF}
