name: 安全检查
on:
  pull_request:
    branches:    
      - master

jobs:
  secret-check:
    name: 安全密钥检查
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --depth=1 origin master
          git checkout -b master
          git checkout -b ${GITHUB_HEAD_REF}
          git branch | xargs echo
          found_secret_id=`git diff master..${GITHUB_HEAD_REF} | grep -E '[^a-zA-Z0-9](AKID[a-zA-Z0-9]{32})([^a-zA-Z0-9]|$)'`
          if [ -n "$found_secret_id" ] ; then
            echo 11111 $found_secret_id
            exit 1
          fi
